version: '3.7'
services:
  todoapp-api:
    build: TodoApp
    image: todoapp-api:1.0
    container_name: todoapp
    #env_file:
    #  - .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: "service_healthy"
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: always

  #db:
  #    image: postgres:17
  #    container_name: postgres_db
  #    environment:
  #      POSTGRES_USER: postgres
  #      POSTGRES_PASSWORD: yourpassword
  #      POSTGRES_DB: expense_tracker
  #    ports:
  #      - "5432:5432"
  #    volumes:
  #      - pgdata:/var/lib/postgresql/data
  #    restart: always
  #    healthcheck:
  #      test: ["CMD-SHELL", "pg_isready -U postgres -d expense_tracker"]
  #      interval: 10s
  #      timeout: 5s
  #      retries: 5
  db:
    container_name: sqlite-db
    image: cleanstart/sqlite3
    volumes:
      - sqlite-data:/db
    ports:
      - "5432:5432"
    #healthcheck:
    #      test: ["CMD-SHELL", "sqlite3"]
    #      interval: 10s
    #      timeout: 5s
    #      retries: 5
    restart: always

volumes:
  sqlite-data:
  #volumes:
  #  pgdata: